In [ ]:
def get_state():
    x, y = st.session_state.agent_pos
    return np.array([x / gw.GRID_WIDTH, y / gw.GRID_HEIGHT])  # Normalisé


In [1]:
from collections import deque
memory = deque(maxlen=2000) 

In [4]:
memory.append(( 0, 0, 0)) # (state, action, reward, next_state)

In [8]:
import numpy as np
z = np.random.randint(0, 25, size=(10, 20))

In [11]:
list(
    z
)

[array([11, 20,  3,  6,  8, 22,  4,  5,  2,  0,  6, 19,  0, 12,  1, 17, 23,
        15, 19, 18]),
 array([23, 16, 18,  1, 22, 18, 19, 15, 23, 16,  0, 10,  2, 11, 18, 23, 10,
         8, 15, 12]),
 array([21,  8,  0,  3,  4, 11,  8,  5, 10,  3, 19, 11, 11, 12,  3, 20, 14,
        21,  8,  8]),
 array([19,  4,  0, 10, 12, 11, 21, 19,  7, 10, 19, 12, 18, 14, 20,  5,  7,
        20, 16, 20]),
 array([ 2, 15, 22, 24,  2, 21,  4,  4, 17,  3, 21, 16, 13,  0, 11,  0,  0,
        13, 16, 14]),
 array([22, 17, 24, 11,  7,  3, 18,  9,  7,  1,  4,  8, 23,  4, 19,  0,  4,
        22,  9, 14]),
 array([22,  8,  5, 20, 20, 17, 15,  6, 21, 20, 20, 18,  6,  5, 12,  7, 21,
         2, 10, 20]),
 array([24, 15,  7, 15,  9,  4,  4, 16, 14, 15,  6, 23,  1, 21,  8,  6, 24,
        18,  1, 10]),
 array([ 1, 17,  3,  4, 21,  3, 12, 22, 14,  7,  8, 15,  1, 14, 16,  5, 15,
        24,  7, 11]),
 array([ 4, 13, 13,  2, 22, 18,  1, 14,  7, 12,  5, 24, 12,  3,  8, 17,  5,
        13,  0, 11])]

In [14]:

import random

random.sample(list(z), min(8, 20))

[array([22, 17, 24, 11,  7,  3, 18,  9,  7,  1,  4,  8, 23,  4, 19,  0,  4,
        22,  9, 14]),
 array([24, 15,  7, 15,  9,  4,  4, 16, 14, 15,  6, 23,  1, 21,  8,  6, 24,
        18,  1, 10]),
 array([ 1, 17,  3,  4, 21,  3, 12, 22, 14,  7,  8, 15,  1, 14, 16,  5, 15,
        24,  7, 11]),
 array([ 2, 15, 22, 24,  2, 21,  4,  4, 17,  3, 21, 16, 13,  0, 11,  0,  0,
        13, 16, 14]),
 array([ 4, 13, 13,  2, 22, 18,  1, 14,  7, 12,  5, 24, 12,  3,  8, 17,  5,
        13,  0, 11]),
 array([11, 20,  3,  6,  8, 22,  4,  5,  2,  0,  6, 19,  0, 12,  1, 17, 23,
        15, 19, 18]),
 array([19,  4,  0, 10, 12, 11, 21, 19,  7, 10, 19, 12, 18, 14, 20,  5,  7,
        20, 16, 20]),
 array([21,  8,  0,  3,  4, 11,  8,  5, 10,  3, 19, 11, 11, 12,  3, 20, 14,
        21,  8,  8])]

In [5]:
memory

deque([(0, 0, 0)], maxlen=2000)

In [ ]:

def train_dqn(model, env, episodes=1000, max_steps=50, gamma=0.95, epsilon=1.0, epsilon_min=0.01, epsilon_decay=0.995, alpha=0.01):
    memory = deque(maxlen=2000)  # Replay Buffer

    for ep in range(episodes):
        env.reset_position( placeholder)
        state = get_state()
        total_reward = 0

        for step in range(max_steps):
            # --- Choix de l'action (epsilon-greedy) ---
            if np.random.rand() < epsilon:
                action_idx = np.random.randint(4)
            else:
                q_values = model.predict(state.reshape(1, -1), verbose=0)
                action_idx = np.argmax(q_values[0])

            action = ACTIONS[action_idx]
            
            # --- Appliquer action ---
            time.sleep(sleep_time)
            agent.move_agent(action)
            x_next, y_next = st.session_state.agent_pos
            reward = st.session_state.R[x_next][y_next]

            next_state = get_state()
            done = (x_next, y_next) == env.goal_pos  # terminal state

            # --- Stocker transition dans le buffer ---
            memory.append((state, action_idx, reward, next_state, done))

            state = next_state
            total_reward += reward

            if done:
                break

        # --- Entraînement par batch ---
        batch_size = min(64, len(memory))
        minibatch = random.sample(memory, batch_size)

        for s, a, r, s_next, d in minibatch:
            target = r
            if not d:
                target += gamma * np.max(model.predict(s_next.reshape(1, -1), verbose=0))
                print("target", target)

            target_f = model.predict(s.reshape(1, -1), verbose=0)
            target_f[0][a] = target  # appliquer l'équation de Bellman

            model.fit(s.reshape(1, -1), target_f, epochs=1, verbose=0)

        # --- Décroissance epsilon ---
        if epsilon > epsilon_min:
            epsilon *= epsilon_decay

        st.sidebar.write(f"Épisode {ep+1}, Récompense totale : {total_reward:.2f}, ε = {epsilon:.3f}")

In [16]:
np.amax(z[0], axis=0)

23

In [ ]:


def train_dqn(model, gw, agent, placeholder, epsilon, gama,alpha=0.01, episodes=10, epsilon_min=0.01, epsilon_decay=0.995):
    memory = deque(maxlen=2000)  # Replay Buffer
    ACTIONS = {
                0:'up', 
                1:'down', 
                2:'left', 
                3:'right'
            }
    max_steps=50

    for ep in range(episodes):
        gw.reset_position( placeholder)
        sleep_time=0.1
        
        
        total_reward = 0

        for step in range(max_steps):
            x, y = st.session_state.agent_pos
            state = get_normalise_state(x, y, gw)
            # --- Choix de l'action (epsilon-greedy) ---
            if np.random.rand() < epsilon:
                action_idx = np.random.randint(4)
            else:
                q_values = model.predict(state.reshape(1, -1), verbose=0)
                action_idx = np.argmax(q_values[0])

            action = ACTIONS[action_idx]
            
            # --- Appliquer action ---
            time.sleep(sleep_time)
            agent.move_agent(action)
            x_next, y_next = st.session_state.agent_pos
            reward = st.session_state.R[x_next][y_next]

            next_state = get_normalise_state(x_next, y_next, gw)
            done = (x_next, y_next) == gw.goal_pos  # terminal state

            # --- Stocker transition dans le buffer ---
            memory.append(((x, y), action_idx, reward, (x_next, y_next), done))

            state = next_state
            total_reward += reward

            if done:
                break

        # --- Entraînement par batch ---
        batch_size = min(64, len(memory))
        minibatch = random.sample(memory, batch_size)

        for s, a, r, s_next, d in minibatch:
            x, y = s
            s = get_normalise_state(s[0], s[1], gw)
            s_next = get_normalise_state(s_next[0], s_next[1], gw)
            
            target = r
            if not d:
                target += gama * np.max(model.predict(s_next, verbose=0))

            target_f = model.predict(s, verbose=0)
            target_f[0][a] = target  # appliquer l'équation de Bellman
            st.session_state.Q[x][y] = target_f[0]

            model.fit(s, target_f, epochs=1, verbose=0)

        # --- Décroissance epsilon ---
        if epsilon > epsilon_min:
            epsilon *= epsilon_decay

        st.sidebar.write(f"Épisode {ep+1}, Récompense totale : {total_reward:.2f}, ε = {epsilon:.3f}")
        
    return model